### ISSUE TITLE
Flume plugin prevents some other plugins from loading

### ISSUE THREAD

**Issue by LordJohnWhorfin** [mpatfield/homebridge-flume#1]
[homebridge_1.3.6.log](https://github.com/bwp91/homebridge-flume/files/7583131/homebridge_1.3.6.log)
[homebridgeconfig.txt](https://github.com/bwp91/homebridge-flume/files/7583177/homebridgeconfig.txt)
Hi Ben,
After installing this new plugin and removing the old one my system is still wonky... There is an error:
[22/11/2021, 09:20:32] ERROR LOADING PLUGIN homebridge-flume:
[22/11/2021, 09:20:32] Error: Cannot find module './package.json'
and then it fails to load most (but not all) of the plugins.
Thanks so much for your help!

**Comment by bwp91** [comment]
Is there any chance we could message on the homebridge discord?

https://discord.gg/bHjKNkN

**Comment by LordJohnWhorfin** [comment]
I'm there as "Lord John Whorfin" but I can't find you :-(

**Comment by LordJohnWhorfin** [comment]
Found you -- I hadn't realized I needed to thumbs-up the rules before gaining access, duh.
