### ISSUE TITLE
Addition of Usage Data in HomeKit

### ISSUE THREAD

**Issue by RadDip** [mpatfield/homebridge-flume#2]
* **Please explain your feature request in a one or two sentences.**
I see that you have added the usage information to the Eve app would be great if they could actually populate in HomeKit

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Flume devices that this relates to?**

Flume 2

* **Anything else?**

**Comment by bwp91** [comment]
> populate in HomeKit
By this do you mean visible in the Home app?

Unfortunately there is no way of showing potentially large numbers like this in the Home app. Only in the Eve app can you show extra HomeKit characteristics like the values you can see.

Apart from the data being visible in the Home app, were you hoping to achieve some extra functionality like using the numbers in an automation/scene or something?

**Comment by RadDip** [comment]
Sorry for the late response.  I did not see that you had responded.

I appreciate the follow up response.   I was not aware that HomeKit was unable to support this functionality.   I was looking at this as more of just a reporting feature than triggering an automation of scene.  

I do see that the requested information is visible in the Eve app.

You can close this out.

Thank you.

**Comment by leeliu** [comment]
I think you can have large numbers in a fan accessory. Similar to this: https://github.com/datMaffin/homebridge-tesla-powerwall/blob/master/src/accessories/powermeter.js#L58

It would be great to see numbers like water usage in the last 1 min and today similar to Flume app, each as fan accessories. Would be a game changer for this homebridge plugin!

<img width="307" alt="Screen Shot 2022-10-09 at 5 50 52 PM" src="https://user-images.githubusercontent.com/1399797/194787304-00478a23-113e-4943-b54f-76448ae841ad.png">
