### ISSUE TITLE
Consistent warning in logs

### ISSUE THREAD

**Issue by RadDip** [mpatfield/homebridge-flume#27]
### What issue do you have? Please be as thorough and explicit as possible.
MFlume BridgeFlumeWARNING[Flume] could not be refreshed as Request failed with status code 429.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
Hoobs

* Which version of Homebridge/HOOBS do you have?
Have hoobs full version with there Raspberry Pi Box running Version 4.2.8. Homebridge Version 1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
HOOBS Box Node 16.17.1

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?
2.0.7  The issue mentioned above has been consistent throughout all versions from starting from when I first used it in Jan of 2022

* Which Flume devices do you have that are causing issues? Please include product models if applicable.
Flume device with wifi Bridge

### Please paste any relevant logs below.

```
[HTTP getDeviceInfo()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"id":"6744446800208432261","type":2,"location_id":70156,"user_id":56164,"bridge_id":"6741896010570553179","oriented":true,"last_seen":"2022-10-16T12:16:08.000Z","connected":true,"battery_level":"high","product":"flume2"}],"count":1,"pagination":null}.
10/16/2022, 8:25:09 AMFlume BridgeFlume[HTTP getDeviceInfo()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"id":"6744446800208432261","type":2,"location_id":70156,"user_id":56164,"bridge_id":"6741896010570553179","oriented":true,"last_seen":"2022-10-16T12:16:08.000Z","connected":true,"battery_level":"high","product":"flume2"}],"count":1,"pagination":null}.
10/16/2022, 8:25:09 AMFlume BridgeFlume[HTTP getLeakInfo()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"active":false}],"count":1,"pagination":null}.
10/16/2022, 8:25:09 AMFlume BridgeFlume[HTTP getLeakInfo()] {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"active":false}],"count":1,"pagination":null}.
```

**Comment by bwp91** [comment]
Hi @RadDip 

Have you changed the refresh interval in the config at all?

**Comment by bwp91** [comment]
Please update to v2.0.8 and restart Homebridge. You may well continue to see this message for up to an hour.
After this time has passed, please let me know if you then continue to see it in your logs.

Also make sure you only have one instance of the plugin running (ie, checking for old, forgotten homebridge installs etc).
