### ISSUE TITLE
Error Starting homebridge-flume on HOOBS Box

### ISSUE THREAD

**Issue by wdbrady** [mpatfield/homebridge-flume#36]
### What issue do you have? Please be as thorough and explicit as possible.
Trying to enable the Flume plugin on my HOOBS box, and get the following error in the logs every time the bridge starts.  

12/17/2022, 10:59:54 AMMainFlumeWARNING***** Disabling plugin. *****
12/17/2022, 10:59:54 AMMainFlumeWARNING***** [HTTP obtainToken()] Cannot read properties of undefined (reading '0') at default.obtainToken (file:///var/lib/hoobs/main/node_modules/homebridge-flume/lib/connection/http.js:93:13). *****

I have run this successfully in native Homebridge.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS?
Yes, HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.2.8, Node 16.18.1, Homebridge 1.5.0 on HOOBS Box

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?
2.0.8

* Which Flume devices do you have that are causing issues? Please include product models if applicable.
Latest generation Flume sensor.  

### Please paste any relevant logs below.

```
12/17/2022, 11:05:45 AMMainFlumeInitialising plugin v2.0.8 | System linux | Node v16.18.1 | HB v1.5.0 | HAPNodeJS v0.10.2...
12/17/2022, 11:05:45 AMMainFlumeWARNINGConfig entry [threshold] is unused and can be removed.
12/17/2022, 11:05:46 AMMainFlumePlugin initialised. Setting up accessories....
12/17/2022, 11:05:47 AMMainFlume[HTTP obtainToken()] "\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003]R]o�@\u0010�+�=[\u0011�]lx��؁� ۘ\u000fW\u0015:�u88��#\u0018���\u001en�H}9ifggG�����Rh\u001ad���\t�U\u0002��\u0014u�\nI�W��\u0001�Zh�7�\u0005MP*�5�#S\u0015�/���5\t\b�8$�([�'(!� ��\u0007\u0012U\u000ee$��h\u001b\u0003�����\u001e!�\u0017%\u000f��@�d\u000e�^<�g?�V\u001ao���`b�Y��\u0014a�z}����*l\u000fO�ݺc�3��GS3��\u001e<sl\u001eBU�s~o�g�;���~��Mc2�\u0013��08��y\u001axR�kt��T����Xp�\u0018�7��y�3z�e��s�����Y�ΞT�e����\u00186f�\u0007��<ŹI|�\u0003UO��P�s��c҇ٮ�qW;���\u001eN�'\u0005�f�<X!U���\b�²��e���s������\u0011&�ޝ�\t|h�\u0016�ve54\u0011+�\u0003�\u0016�qj�H*��Z�_��t�h3Lf:�w>�\u001a�c\u0005\u0016�\u0012�5\u001d\u0016\u0017����/��@\u0006��+ye%\u0011����E?\u0003[�;�8\u0002\u0000\u0000".
12/17/2022, 11:05:47 AMMainFlumeWARNING***** Disabling plugin. *****
12/17/2022, 11:05:47 AMMainFlumeWARNING***** [HTTP obtainToken()] Cannot read properties of undefined (reading '0') at default.obtainToken (file:///var/lib/hoobs/main/node_modules/homebridge-flume/lib/connection/http.js:93:13). *****
```

**Comment by bwp91** [comment]
Hi @wdbrady 

Is this still an issue you are experiencing?

Can we message directly on discord to try and see what is causing this?

https://discord.gg/cMGhNtZ3tW
