### ISSUE TITLE
Flume plugin doesnt send notifications to Home (IOS or MAC)

### ISSUE THREAD

**Issue by kaduffey** [mpatfield/homebridge-flume#59]
### What issue do you have? Please be as thorough and explicit as possible.
Flume not sending alerts to Homekit devices. For example when wife take super long shower it reports a leak via the Flume App, but not home (just says 'SAFE')

### Details of your setup to a Homekit with multiple Homepds (OG and Mini), Apple TV 4K gen 3 - Thread and matter supported.
Inonexx Xome Homebridge v 

OS	Debian GNU/Linux Bullseye (11)
Hostname	Xome
Node.js Version	[v18.15.0](https://homebridge.io/w/JTKEF)

LOGS:
[3/19/2023, 5:14:40 AM] Loaded plugin: homebridge-flume@3.0.1
[3/19/2023, 5:14:40 AM] Registering platform 'homebridge-flume.Flume'
[3/19/2023, 5:14:42 AM] [Flume] Initializing Flume platform...
[3/19/2023, 5:14:42 AM] [Flume] Initialising plugin v3.0.1 | System linux | Node v18.15.0 | HB v1.6.0 | HAPNodeJS v0.11.0...
[3/19/2023, 5:14:43 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 24E2) is running on port xxxxx.
[3/19/2023, 5:14:44 AM] [Flume] [Flume] initialised with id [6805721315408465078].
[3/19/2023, 5:14:44 AM] [Flume] ✓ Setup complete. Have a feature request? Visit https://bit.ly/hb-flume-issues to ask!

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-flume) do you have? Has the issue started since upgrading from a previous version?

* Which Flume devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @kaduffey could you update to the beta version of the plugin? 
Currently the only difference between the version you are running and the beta version is that it will show more detailed entries in the homebridge log.
I _really_ need to see homebridge logs when you are expecting the home app to shout an alert when it isn't currently.
Could you update to the beta and kindly ask your wife to take a long shower and show me all the logs that appear?

**Comment by kaduffey** [comment]
In ignorance. How do I install the beta via Homebridge UI?

**Comment by bwp91** [comment]
ah there is a wiki link here to help 🙂
https://github.com/bwp91/homebridge-flume/wiki/Beta-Version

**Comment by kaduffey** [comment]
ok, done

***@***.***:/var/lib/homebridge $ su root
Password:**************************
***@***.***:/var/lib/homebridge# npm install ***@***.*** -g

added 12 packages in 8s


Next Alert I will grab the logs

**Comment by kaduffey** [comment]
from the below log entries it appears it loaded the beta (yes I restarted
Homebridge)

But on the alert at 5:57a PT just now there is zero log entries

It said I didnt have to uninstall before loading the beta - do I?

**Comment by kaduffey** [comment]
reinstalling from the "Wrench" icon of HB 1.60 plugins page and am now
getting detailed logs.

Heading upstairs to turn on shower

**Comment by kaduffey** [comment]
attached log shows no alert - comments embedded in attached log

On Tue, Mar 21, 2023 at 12:38 PM Kevin Duffey ***@***.***> wrote:

> reinstalling from the "Wrench" icon of HB 1.60 plugins page and am now
> getting detailed logs.
>
> Heading upstairs to turn on shower
>
>
[kaduffey Flume2 detail logs - no alert to Homebridge or Home app.pdf](https://github.com/bwp91/homebridge-flume/files/11033620/kaduffey.Flume2.detail.logs.-.no.alert.to.Homebridge.or.Home.app.pdf)

>
>

**Comment by bwp91** [comment]
Hi @kaduffey 

Please can you (1) change your flume password, (2) update to the new version and (3) let me know when you have done this?

**Comment by kaduffey** [comment]
I got to the beta and ran a test 2 days ago, the logs are attached in my
last message. I reverted to stable Wednesday night when the debug mode was
flooding my logs.

Why am I changing my PWD?  If I look in home+ or Controller I see all the
stats, just not alerts.

**Comment by bwp91** [comment]
I advised because your logs contains credentials to allow anyone to log into your account. 
The new version redacts this data.
This is why i asked for you to tell me when done

**Comment by kaduffey** [comment]
hanged, and homebridge restarted with new PWD for Flume

You should never be capturing passwords or userid's (client IDs,
secrets etc in log). PLease auto redact those or dont log them at all

**Comment by kaduffey** [comment]
*changed

3.02 latest also installed

**Comment by bwp91** [comment]
> hanged, and homebridge restarted with new PWD for Flume You should never be capturing passwords or userid's (client IDs, secrets etc in log). PLease auto redact those or dont log them at all
> […](#)

Yes thank you. I am aware and this why i released a new version of the plugin which does redact this.

I do not own any flume devices but took this plugin on with best intentions

**Comment by bwp91** [comment]
Your comments have made me realise that I am probably not ideal as a maintainer of this plugin.

Have made a request for this plugin to be pushed to the unmaintained plugins section of Homebridge, and hopefully, someone better equipped can take it over!

**Comment by kaduffey** [comment]
no worries. No reason to stop. I can be your guinea pig, I do have a gen2 flumeOn Mar 24, 2023, at 6:24 PM, Ben ***@***.***> wrote:﻿
Your comments have made me realise that I am probably not ideal as a maintainer of this plugin.
Have made a request for this plugin to be pushed to the unmaintained plugins section of Homebridge, and hopefully, someone better equipped can take it over!

**Comment by kaduffey** [comment]
I dont think you should give up. Your response is great, and you fixed what I mentioned. Sorry if I came across strong. Happy to be your tester on my flume.  Do they use Flume in England?

**Comment by kaduffey** [comment]
Looked at this again, and I think I saw the icon flash on/off - I turned off water right after I got the flume based alert?  Could it be its only on when the 'leak' is active and doesnt leave a persistent alert? Or perhaps I dont wait long enough for your polling of flume to occur?
