### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by PappyChappy1** [mpatfield/homebridge-flume#74]
No errors are occurring, but I am receiving a warning that Node 20 is not supported - do you plan on updating the plugin to not warn about this?

**Comment by russellquinn** [comment]
+1

**Comment by PappyChappy1** [comment]
@bwp91 is it possible to just bump this node version? Plugin is working but it throws an alert when running

**Comment by PappyChappy1** [comment]
@bwp91 Following up on this - also not sure if there will be issues with homebridge 2.0 breaking dependancies for plugins once it goes live anyways

**Comment by bwp91** [comment]
Can anyone try `3.0.3-beta.0` beta version?

**Comment by PappyChappy1** [comment]
@bwp91 looks to fix the Node warning, and it seems to be working on homebridge 2.0...it still gets a warning that 2.0 may break plugins but that might just be for all plugins? Not sure if it means yours has any potential dependency issues.  Thank you for fixing!

**Comment by bwp91** [comment]
thanks. just released v3.0.3

- updated node versions to v18/v20/v22.
- updated dependencies
- updated to support homebridge v2
